package login;


import java.awt.event.KeyEvent;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DemoFrame extends javax.swing.JFrame {

    private Connection con = DBConnection.getConnection();
    
    public DemoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInBtn = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        pwdField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        signeUpBtn = new javax.swing.JButton();
        seePwd = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        logInBtn.setBackground(new java.awt.Color(90, 186, 158));
        logInBtn.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        logInBtn.setForeground(new java.awt.Color(255, 254, 244));
        logInBtn.setText("LogIn");
        logInBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 254, 244), 3));
        logInBtn.setBorderPainted(false);
        logInBtn.setFocusable(false);
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });
        logInBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logInBtnKeyPressed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(90, 186, 158));
        userLabel.setText("Username : ");

        userField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        userField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 186, 158), 2));
        userField.setMinimumSize(new java.awt.Dimension(64, 30));
        userField.setPreferredSize(new java.awt.Dimension(64, 30));
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        userField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userFieldKeyPressed(evt);
            }
        });

        pwdField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pwdField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 186, 158), 2));
        pwdField.setMinimumSize(new java.awt.Dimension(64, 30));
        pwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldActionPerformed(evt);
            }
        });
        pwdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdFieldKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\icons8-login-100.png")); // NOI18N
        jLabel2.setText("Login");

        pwdLabel.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        pwdLabel.setForeground(new java.awt.Color(90, 186, 158));
        pwdLabel.setText("Password : ");

        signeUpBtn.setBackground(new java.awt.Color(255, 254, 244));
        signeUpBtn.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        signeUpBtn.setForeground(new java.awt.Color(90, 186, 158));
        signeUpBtn.setText("SignUp");
        signeUpBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signeUpBtn.setBorderPainted(false);
        signeUpBtn.setFocusable(false);
        signeUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signeUpBtnActionPerformed(evt);
            }
        });

        seePwd.setBackground(new java.awt.Color(90, 186, 158));
        seePwd.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        seePwd.setForeground(new java.awt.Color(255, 254, 244));
        seePwd.setText("See ");
        seePwd.setBorder(null);
        seePwd.setFocusable(false);
        seePwd.setPreferredSize(new java.awt.Dimension(55, 22));
        seePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePwdActionPerformed(evt);
            }
        });
        seePwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seePwdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(logInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pwdLabel)
                                    .addComponent(userLabel))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(signeUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdLabel)
                    .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signeUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
//        System.out.println("Hello "+userField.getText()+" Your pwd is : ");
//        
//        System.out.println();

pwdField.setEchoChar('•');

String username=userField.getText();
String pwd=String.valueOf(pwdField.getPassword());
    
    if(username.equals("")){
        String msg = "Empty Username";
        
        if(pwd.equals("")){
            msg+=" and Password!";
        }
        else{
            msg+=" !";
        }
        JOptionPane.showMessageDialog(this,msg ,"logging in Failed!",JOptionPane.ERROR_MESSAGE);
        return;
    }
    else{
        if(pwd.equals("")){
            JOptionPane.showMessageDialog(this,"Empty Password !" ,"logging in Failed!",JOptionPane.ERROR_MESSAGE);
        return;
        }
        
    }
    
    String query="SELECT * FROM users WHERE usename = '"+username+"'";
    
    try(PreparedStatement pst = con.prepareStatement(query)){
        
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()){
            if(rs.getString(3).equals(pwd)){

                JOptionPane.showMessageDialog(this, "loging in seccesfully !", "loggedIn", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                
//                    System.out.println("\t========================================");
//                      System.out.println("\t This is the Pwd You Entered : "+pwd);
//                    System.out.println("\t========================================");

                    JOptionPane.showMessageDialog(this,"Wrong Password for the user : "+username+" !" ,"logging in Failed!",JOptionPane.ERROR_MESSAGE);
      
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"This Account Does not exist" ,"logging in Failed!",JOptionPane.ERROR_MESSAGE);      
        }
        
    }catch(SQLException e){
        e.printStackTrace();
    }
    
    
    
    
    }//GEN-LAST:event_logInBtnActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void pwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldActionPerformed

    private void signeUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signeUpBtnActionPerformed
        new SigneUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signeUpBtnActionPerformed

    private void seePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePwdActionPerformed
  
        pwdField.setEchoChar(seePwd.isSelected() ? '\0' : '•');
    }//GEN-LAST:event_seePwdActionPerformed

    private void seePwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seePwdKeyPressed

    }//GEN-LAST:event_seePwdKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void logInBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logInBtnKeyPressed
        
    }//GEN-LAST:event_logInBtnKeyPressed

    private void pwdFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logInBtn.doClick();
        }
    }//GEN-LAST:event_pwdFieldKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    
    }//GEN-LAST:event_formKeyPressed

    private void userFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logInBtn.doClick();
        }
    }//GEN-LAST:event_userFieldKeyPressed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logInBtn;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JCheckBox seePwd;
    private javax.swing.JButton signeUpBtn;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
